In [14]:
import numpy as np
import pandas as pd 
messages = pd.read_csv(r'C:\Users\Nitin Flavier\Desktop\Data Nexus\Data Science\ML_BootCamp\ML_Algos\NLP\Data\smsSpamCollection',sep='\t',names=['label','message'])
messages.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [2]:
# Data cleaning and processing 
import re
import nltk 
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Nitin
[nltk_data]     Flavier\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [6]:
from nltk.corpus import stopwords 
from nltk.stem import WordNetLemmatizer 
lemmatizer = WordNetLemmatizer()

n = len(messages)
stop_words = stopwords.words('english')

In [20]:
corpus = [] 
for i in range(n):
    message = re.sub('[^a-zA-Z]',' ',messages['message'][i])
    message = message.lower()
    message = [lemmatizer.lemmatize(w,pos='v') for w in message.split(' ') if (w != '') and (w not in stop_words)]
    message = ' '.join(message)
    corpus.append(message)
print(corpus)

['go jurong point crazy available bugis n great world la e buffet cine get amore wat', 'ok lar joke wif u oni', 'free entry wkly comp win fa cup final tkts st may text fa receive entry question std txt rate c apply', 'u dun say early hor u c already say', 'nah think go usf live around though', 'freemsg hey darling week word back like fun still tb ok xxx std chgs send rcv', 'even brother like speak treat like aid patent', 'per request melle melle oru minnaminunginte nurungu vettam set callertune callers press copy friends callertune', 'winner value network customer select receivea prize reward claim call claim code kl valid hours', 'mobile months u r entitle update latest colour mobiles camera free call mobile update co free', 'gonna home soon want talk stuff anymore tonight k cry enough today', 'six chance win cash pound txt csh send cost p day days tsandcs apply reply hl info', 'urgent week free membership prize jackpot txt word claim c www dbuk net lccltd pobox ldnw rw', 'search righ

### Bag of Words:


In [184]:
y = np.where(messages['label'] == 'spam',1,0)
y

array([0, 0, 1, ..., 0, 0, 0])

In [50]:
# train-test split 
from sklearn.model_selection import train_test_split 
from sklearn.feature_extraction.text import CountVectorizer

X_train,X_test,y_train,y_test = train_test_split(corpus,y,test_size=0.33,random_state=32) 

cv = CountVectorizer(max_features=500,ngram_range=(1,2))

X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray()

In [38]:
cv.vocabulary_

{'go': 161,
 'point': 334,
 'great': 170,
 'world': 483,
 'get': 157,
 'wat': 464,
 'ok': 299,
 'lar': 222,
 'wif': 473,
 'free': 148,
 'entry': 132,
 'win': 475,
 'st': 399,
 'may': 256,
 'text': 414,
 'receive': 354,
 'question': 346,
 'txt': 446,
 'rate': 348,
 'apply': 18,
 'dun': 120,
 'say': 366,
 'early': 122,
 'already': 9,
 'think': 422,
 'live': 238,
 'around': 20,
 'though': 424,
 'hey': 192,
 'week': 467,
 'word': 481,
 'back': 29,
 'like': 234,
 'fun': 155,
 'still': 402,
 'xxx': 490,
 'send': 374,
 'even': 134,
 'brother': 46,
 'speak': 396,
 'per': 316,
 'set': 377,
 'friends': 151,
 'network': 283,
 'customer': 90,
 'select': 372,
 'prize': 341,
 'claim': 68,
 'call': 51,
 'code': 74,
 'valid': 454,
 'hours': 201,
 'mobile': 268,
 'update': 449,
 'latest': 226,
 'colour': 77,
 'camera': 54,
 'co': 72,
 'free call': 149,
 'gonna': 165,
 'home': 196,
 'soon': 392,
 'want': 463,
 'talk': 411,
 'stuff': 406,
 'tonight': 434,
 'enough': 130,
 'today': 429,
 'chance': 60,
 'c

In [51]:
from sklearn.naive_bayes import MultinomialNB 

nb = MultinomialNB()
model = nb.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [52]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print("Classification Report: ",classification_report(y_test,y_pred))
print()
print("Confusion Matrix: \n",confusion_matrix(y_test,y_pred))
print()
print("Accuracy Score: ",accuracy_score(y_test,y_pred))

Classification Report:                precision    recall  f1-score   support

           0       0.99      0.99      0.99      1587
           1       0.91      0.92      0.92       252

    accuracy                           0.98      1839
   macro avg       0.95      0.95      0.95      1839
weighted avg       0.98      0.98      0.98      1839


Confusion Matrix: 
 [[1564   23]
 [  20  232]]

Accuracy Score:  0.9766177270255574


### TF-IDF

In [46]:
### create the model 
from sklearn.feature_extraction.text import TfidfVectorizer 

tf = TfidfVectorizer(max_features=500,ngram_range=(1,2))

X_train,X_test,y_train,y_test = train_test_split(corpus,y,test_size=0.33,random_state=32)
X_train = tf.fit_transform(X_train).toarray()
X_test = tf.transform(X_test).toarray()

In [48]:
model2 = nb.fit(X_train,y_train)
y_pred2 = model2.predict(X_test)

print("Accuracy Score ",accuracy_score(y_test,y_pred2))
print()
print("Classification Report ",classification_report(y_test,y_pred2))
print()
print("Confusion matrix ",confusion_matrix(y_test,y_pred2))


Accuracy Score  0.9733550842849374

Classification Report                precision    recall  f1-score   support

           0       0.98      0.99      0.98      1587
           1       0.96      0.84      0.90       252

    accuracy                           0.97      1839
   macro avg       0.97      0.92      0.94      1839
weighted avg       0.97      0.97      0.97      1839


Confusion matrix  [[1578    9]
 [  40  212]]


### Word2Vec

In [54]:
from gensim.models import Word2Vec, KeyedVectors 
import gensim.downloader as api 

w2v = api.load('word2vec-google-news-300')

In [160]:
messages.isna().sum()

label      0
message    0
dtype: int64

In [ ]:
corpus = [] 
n = messages.shape[0]
for i in range(n):
    message = re.sub('[^a-zA-Z]',' ',messages['message'][i])
    message = message.lower()
    message = [lemmatizer.lemmatize(w,pos='v') for w in message.split(' ')]
    message = ' '.join(message)
    corpus.append(message)

print(messages.shape)
print(len(corpus))

(5572, 2)
5572


In [210]:
# representing every sentence from the word corpus
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

words = []
index_tobe_deleted = []

# in Word2Vec we represent each word in terms of feature_values, then for the sentence

for i,sent in enumerate(corpus):
    token = sent_tokenize(sent) # it will convert the sentence into words
    flag = 1
    for sent in token:
        flag = 0
        words.append(simple_preprocess(sent))
    
    if(flag):
        index_tobe_deleted.append(i)

print(index_tobe_deleted)
print(len(words))
print(words)

[1612, 3376, 4824]
5569
[['go', 'until', 'jurong', 'point', 'crazy', 'available', 'only', 'in', 'bugis', 'great', 'world', 'la', 'buffet', 'cine', 'there', 'get', 'amore', 'wat'], ['ok', 'lar', 'joke', 'wif', 'oni'], ['free', 'entry', 'in', 'wkly', 'comp', 'to', 'win', 'fa', 'cup', 'final', 'tkts', 'st', 'may', 'text', 'fa', 'to', 'to', 'receive', 'entry', 'question', 'std', 'txt', 'rate', 'apply', 'over'], ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'], ['nah', 'don', 'think', 'he', 'go', 'to', 'usf', 'he', 'live', 'around', 'here', 'though'], ['freemsg', 'hey', 'there', 'darling', 'it', 'be', 'week', 'now', 'and', 'no', 'word', 'back', 'like', 'some', 'fun', 'you', 'up', 'for', 'it', 'still', 'tb', 'ok', 'xxx', 'std', 'chgs', 'to', 'send', 'to', 'rcv'], ['even', 'my', 'brother', 'be', 'not', 'like', 'to', 'speak', 'with', 'me', 'they', 'treat', 'me', 'like', 'aid', 'patent'], ['as', 'per', 'your', 'request', 'melle', 'melle', 'oru', 'minnaminunginte', 'nurungu', 'vett

In [152]:
import gensim

# lets train 
model = gensim.models.Word2Vec(words,epochs=500)
# vocabulary
model.wv.index_to_key

['be',
 'to',
 'you',
 'the',
 'and',
 'in',
 'have',
 'me',
 'my',
 'it',
 'do',
 'for',
 'get',
 'call',
 'your',
 'of',
 'that',
 'go',
 'on',
 'now',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'at',
 'will',
 'ur',
 'if',
 'with',
 'no',
 'just',
 'this',
 'come',
 'gt',
 'lt',
 'how',
 'up',
 'when',
 'ok',
 'what',
 'know',
 'free',
 'from',
 'send',
 'all',
 'out',
 'll',
 'like',
 'time',
 'love',
 'want',
 'good',
 'day',
 'then',
 'there',
 'he',
 'say',
 'its',
 'only',
 'think',
 'tell',
 'take',
 'text',
 'need',
 'win',
 'see',
 'txt',
 'as',
 'make',
 'one',
 'by',
 'stop',
 'don',
 'she',
 'home',
 'about',
 'reply',
 'lor',
 'today',
 'sorry',
 'still',
 'back',
 'da',
 'dont',
 'our',
 'mobile',
 'phone',
 'please',
 'hi',
 'meet',
 'work',
 'new',
 'they',
 'later',
 'miss',
 'pls',
 'her',
 'ask',
 'any',
 'give',
 'some',
 'dear',
 'week',
 'message',
 'here',
 'who',
 'wait',
 'well',
 'where',
 'leave',
 'night',
 're',
 'try',
 'much',
 'claim',
 'an',
 'grea

In [153]:
print(model.corpus_count)
print(model.epochs)

5566
500


In [154]:
# to see similar words
model.wv.similar_by_word('kid')

[('parent', 0.40932685136795044),
 ('colleagues', 0.39114925265312195),
 ('yoga', 0.30269119143486023),
 ('theatre', 0.2759811282157898),
 ('apartment', 0.2716425657272339),
 ('convey', 0.27027082443237305),
 ('rent', 0.266505628824234),
 ('shoot', 0.26560819149017334),
 ('sleep', 0.2579251527786255),
 ('nimya', 0.25770440697669983)]

In [155]:
model.wv['good']

array([-0.14829987, -1.3962287 ,  0.23978926,  4.400484  ,  0.70137703,
        1.3268657 , -0.39252472, -1.2556036 , -0.93757784, -1.8784881 ,
       -0.14365034,  1.0477011 ,  0.18805347,  1.9368535 , -1.6558552 ,
       -0.355068  ,  0.52433836,  3.3472238 , -0.4850567 ,  2.0248616 ,
       -1.0902536 ,  1.1203417 , -0.02532306, -4.097616  ,  1.1593188 ,
       -0.5789791 , -1.1840249 , -2.080463  , -0.08840363,  1.1587911 ,
        0.97531   ,  1.2304434 ,  1.8288463 , -1.314621  , -0.50109786,
       -0.43736324,  1.2601992 ,  3.1550534 , -0.18700834, -0.75088567,
        4.049805  ,  0.00676168,  1.5751542 , -0.94740963, -0.08565727,
        2.215447  , -2.9762743 , -1.3602365 ,  0.55679435,  0.08040184,
        0.79238963,  1.2636158 , -1.6174188 ,  1.8162487 , -1.4316655 ,
        1.8592073 , -0.7127406 , -3.2870247 , -1.226017  , -1.0951189 ,
       -1.361973  ,  1.0850133 , -0.44310823, -0.49826977, -1.8898671 ,
        1.2619065 , -0.9575729 , -2.8802726 , -1.7484038 ,  4.12

In [156]:
def avgWord2Vec(sentence):

    return np.mean([model.wv[w] for w in sentence if w in model.wv.index_to_key], axis=0)
    

In [98]:
pip install tqdm

Note: you may need to restart the kernel to use updated packages.


In [212]:
from tqdm import tqdm

X = []

n = len(words)
y_index = []

for i in tqdm(range(n)):
    
    ele = avgWord2Vec(words[i])
    if not np.any(np.isnan(ele)):
        X.append(ele)
    else:
        y_index.append(i)

print(len(X))
print(len(y_index))
print(X[0][0:10])

  0%|          | 0/5569 [00:00<?, ?it/s]c:\Users\Nitin Flavier\anaconda3\Lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\Nitin Flavier\anaconda3\Lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5569/5569 [00:00<00:00, 11302.06it/s]

5557
12
[ 0.05019444  0.24530736 -0.95045775  0.28211135  0.7554417   0.07473803
  0.1198442   1.066164   -0.06035794  0.7676996 ]


In [173]:
print("Input Size: ",len(X))
print("Feature Size: ",len(X[0])) 

Input Size:  5569
Feature Size:  100


In [213]:
y = np.where(messages['label'] == 'spam',1,0)
y = np.delete(y,index_tobe_deleted)
y = np.delete(y,y_index)


In [214]:
print(len(y))
len(X)

5557


5557

In [224]:
# independent features:
df = pd.DataFrame()

for i in range(len(X)):
    tempdf = pd.DataFrame(X[i].reshape(1,-1))
    df = pd.concat([df,tempdf],ignore_index=True)

df.head()

0         1         2         3         4         5         6   \
0  0.050194  0.245307 -0.950458  0.282111  0.755442  0.074738  0.119844   
1  0.088023  1.443379 -0.565123  0.501175 -0.172586 -1.283378  2.220993   
2 -0.103687 -0.122201 -1.189367 -1.781626 -0.251154  0.778348  0.057396   
3 -0.979676  0.980594  0.300149  2.354064 -0.807348 -1.003471  1.013138   
4 -0.561779  0.770589  1.470811  0.195374 -0.958552  0.653699 -0.125065   

         7         8         9   ...        90        91        92        93  \
0  1.066164 -0.060358  0.767700  ... -0.384350  0.037537  0.132395  0.235302   
1  0.255423  0.406254  0.271552  ...  1.375253 -0.270489  0.384241  0.775949   
2  0.443436  0.368042 -0.904520  ...  0.908565 -0.472807 -0.228958  0.211868   
3 -1.370803 -0.637153 -0.500621  ...  0.878743 -0.020309  0.752181 -1.162386   
4  0.093540 -1.605178 -0.878344  ... -0.502558 -0.020139 -0.778348 -0.397178   

         94        95        96        97        98        99  
0  0.469395  1.605625  0.317555 -0.138624 -0.329461  0.059874  
1 -0.565222 -0.823647  1.158670 -0.069203 -0.097566 -2.925565  
2 -0.136578 -0.126696 -0.511546 -0.036366  0.234842 -0.035881  
3 -0.203841 -0.451657  0.201604  1.535835  0.801342  0.042717  
4 -0.653255 -0.218852 -0.841445  0.897722 -0.236218  0.240822  

[5 rows x 100 columns]

In [226]:
X_train,X_test,y_train,y_test = train_test_split(df,y,test_size=0.33,random_state=32)

In [227]:
from sklearn.ensemble import RandomForestClassifier 
rf = RandomForestClassifier()

rf.fit(X_train,y_train)

RandomForestClassifier()

In [228]:
y_pred = rf.predict(X_test)

print("Accuracy: ",accuracy_score(y_test,y_pred))
print()
print("Classification Report: ",classification_report(y_test,y_pred))
print()
print("Confusion Matrix: ",confusion_matrix(y_test,y_pred))

Accuracy:  0.9825517993456925

Classification Report:                precision    recall  f1-score   support

           0       0.98      1.00      0.99      1596
           1       0.97      0.89      0.93       238

    accuracy                           0.98      1834
   macro avg       0.98      0.94      0.96      1834
weighted avg       0.98      0.98      0.98      1834


Confusion Matrix:  [[1590    6]
 [  26  212]]
